server:
  port: 3333
spring:
  application:
    name: zuul-service

eureka.instance.prefer-ip-address: true
eureka.instance.instance-id: ${spring.application.name}:${spring.cloud.client.ip-address}:${server.port}
eureka.client.serviceUrl.defaultZone: http://root:root@localhost:9999/eureka/

eureka.instance.lease-renewal-interval-in-seconds: 5
eureka.instance.lease-expiration-duration-in-seconds: 10

zuul:
  routes:
    auth-service:
      path: /uaa/**
      serviceId: auth-service

